#############################################################################
# Makefile for building: work
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 6? 4 19:21:11 2016
# Project:  work.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.7.3/bin/qmake -o Makefile work.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.3/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.3/include/QtCore -I/usr/local/Trolltech/Qt-4.7.3/include/QtGui -I/usr/local/Trolltech/Qt-4.7.3/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.3/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.3/lib -lQtGui -L/usr/local/Trolltech/Qt-4.7.3/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.7.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainWindow.cpp moc_mainWindow.cpp
OBJECTS       = main.o \
		mainWindow.o \
		moc_mainWindow.o
DIST          = /usr/local/Trolltech/Qt-4.7.3/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/include_source_dir.prf \
		work.pro
QMAKE_TARGET  = work
DESTDIR       = 
TARGET        = work

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: work.pro  /usr/local/Trolltech/Qt-4.7.3/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.3/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.3/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.7.3/lib/libQtCore.prl
	$(QMAKE) -o Makefile work.pro
/usr/local/Trolltech/Qt-4.7.3/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.3/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.3/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.7.3/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile work.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/work1.0.0 || $(MKDIR) .tmp/work1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/work1.0.0/ && $(COPY_FILE) --parents mainWindow.h .tmp/work1.0.0/ && $(COPY_FILE) --parents main.cpp mainWindow.cpp .tmp/work1.0.0/ && $(COPY_FILE) --parents mainWindow.ui .tmp/work1.0.0/ && (cd `dirname .tmp/work1.0.0` && $(TAR) work1.0.0.tar work1.0.0 && $(COMPRESS) work1.0.0.tar) && $(MOVE) `dirname .tmp/work1.0.0`/work1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/work1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainWindow.cpp
moc_mainWindow.cpp: ui_mainWindow.h \
		mainWindow.h
	/usr/local/Trolltech/Qt-4.7.3/bin/moc $(DEFINES) $(INCPATH) mainWindow.h -o moc_mainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainWindow.h
ui_mainWindow.h: mainWindow.ui
	/usr/local/Trolltech/Qt-4.7.3/bin/uic mainWindow.ui -o ui_mainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainWindow.h \
		ui_mainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindow.o: mainWindow.cpp mainWindow.h \
		ui_mainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

