######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 13 23:41:05 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ./mySQL

# Input
HEADERS += mainWindow.h formDlg.h mydb.h
FORMS += mainWindow.ui formDlg.ui
SOURCES += main.cpp mainWindow.cpp mydb.cpp formDlg.cpp
